import "./integration-schema.test";
import "./seamer-capability.test";
import "./capability-fields.test";
import "./device-manifests.test";
import "./schedule-import.test";
import "./schedule-adapters.test";
import "./security.test";
import "./backup-policy.test";
import "./logger-security.test";
import "./obs-secret-settings.test";
import "./authenticated-command.test";
import "./postgresql-live.test";
import "./bundle-source-independence.test";
import "./dashboard-ui-contract.test";
import "./dashboard-ui-reference.test";
import "./dashboard-ui-device.test";
import "./dashboard-ui-operations.test";
import { runTests } from "./test-harness";

void runTests();
